-- このファイルは初期セットアップ時のスナップショットとして残していますが、
-- 現在のスキーマの正は src/lib/db/schema.ts と supabase/migrations/ です。
-- テーブル追加・変更は `npm run db:generate` でマイグレーションを生成してください。
--
-- 認証機能は撤廃済みです（社内共有DBのため RLS は使用しません）。
